FROM node:alpine AS runner
WORKDIR /app

ENV NODE_ENV development
RUN apk add --no-cache libc6-compat
COPY . .
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
RUN chown -R nextjs:nodejs /app/.next
USER nextjs

RUN npm install
CMD ["npm", "run", "dev"]